import pyautogui as pg
import time
pg.hotkey('win' , 'e')
time.sleep(1)
pg.click (99,277)
pg.doubleClick (316,427)
time.sleep(1)
pg.hotkey('ctrl', 'a')
pg.hotkey('ctrl', 'c')
pg.hotkey('alt', 'f4')
pg.hotkey('win' , 'r')
pg.write ('notepad')
time.sleep(1)
pg.press ('enter')
time.sleep (3)
pg.hotkey('ctrl','v')
pg.hotkey ('ctrl' , 's')
time.sleep (3)
pg.click (710, 582)
pg.write ('123')
time.sleep (1)
pg.press ('enter')
